workflows:
  ios_appstore:
    name: iOS App Store (Capacitor)
    instance_type: mac_mini_m2
    max_build_duration: 60

    environment:
      xcode: 15.4
      vars:
        XCODE_WORKSPACE: "ios/App/App.xcworkspace"
        XCODE_SCHEME: "App"

    scripts:
      - name: Bootstrap minimal project files
        script: |
          set -euxo pipefail
          # Minimal package.json so npm works
          test -f package.json || echo '{ "name":"glowup","version":"1.0.0","private":true }' > package.json
          # Capacitor config
          cat > capacitor.config.json <<'EOF'
          {
            "appId": "com.mathe.glowup",
            "appName": "GlowUp Money",
            "webDir": "web",
            "bundledWebRuntime": false
          }
          EOF
          # Tiny web so Capacitor has something to copy
          mkdir -p web
          test -f web/index.html || echo '<!doctype html><title>GlowUp</title><body>✅ Capacitor</body>' > web/index.html

      - name: Install JS deps & Capacitor
        script: |
          set -euxo pipefail
          npm i -D @capacitor/cli @capacitor/core @capacitor/ios

      - name: Sync iOS platform
        script: |
          set -euxo pipefail
          npx cap add ios || true
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          set -euxo pipefail
          cd ios/App
          pod install --no-repo-update
          cd ../..

      - name: Extract signing info (team, bundle id, profile name)
        script: |
          set -euxo pipefail
          PROFILES_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          PROFILE_PATH=$(ls "$PROFILES_DIR"/*.mobileprovision | head -n1)
          echo "Using provisioning profile at: $PROFILE_PATH"
          security cms -D -i "$PROFILE_PATH" > build/profile.plist
          TEAM_ID=$(/usr/libexec/PlistBuddy -c 'Print :TeamIdentifier:0' build/profile.plist)
          PROFILE_NAME=$(/usr/libexec/PlistBuddy -c 'Print :Name' build/profile.plist)
          APP_ID=$(/usr/libexec/PlistBuddy -c 'Print :Entitlements:application-identifier' build/profile.plist)
          BUNDLE_FROM_PROFILE="${APP_ID#*.}"
          # Export vars for later steps
          echo "TEAM_ID=$TEAM_ID"            >> $CM_ENV
          echo "PROFILE_NAME=$PROFILE_NAME"  >> $CM_ENV
          echo "BUNDLE_ID=$BUNDLE_FROM_PROFILE" >> $CM_ENV
          echo "→ TEAM_ID: $TEAM_ID"
          echo "→ PROFILE_NAME: $PROFILE_NAME"
          echo "→ BUNDLE_ID: $BUNDLE_FROM_PROFILE"

      - name: Set bundle id + version in Info.plist
        script: |
          set -euxo pipefail
          PLIST=ios/App/App/Info.plist
          /usr/libexec/PlistBuddy -c "Add :CFBundleIdentifier string ${BUNDLE_ID}" "$PLIST" || \
          /usr/libexec/PlistBuddy -c "Set :CFBundleIdentifier ${BUNDLE_ID}" "$PLIST"
          /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string 1.0.0" "$PLIST" || true
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.0.0" "$PLIST" || true
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${BUILD_NUMBER}" "$PLIST" || true
          /usr/libexec/PlistBuddy -c "Print" "$PLIST" | sed -n '1,120p' || true

      - name: Archive (Release)
        script: |
          set -euxo pipefail
          xcodebuild \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/App.xcarchive \
            clean archive \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            CODE_SIGN_STYLE=Manual \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME"

      - name: Export IPA
        script: |
          set -euxo pipefail
          cat > ExportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0"><dict>
            <key>method</key><string>app-store</string>
            <key>signingStyle</key><string>manual</string>
            <key>provisioningProfiles</key><dict>
              <key>${BUNDLE_ID}</key><string>${PROFILE_NAME}</string>
            </dict>
          </dict></plist>
          EOF
          xcodebuild -exportArchive -archivePath build/App.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath build

    artifacts:
      - build/*.ipa
