workflows:
  ios_simulator:
    name: iOS Simulator Build (no signing)
    instance_type: mac_mini_m2
    max_build_duration: 30

    environment:
      xcode: 15.4

    scripts:
      - name: Ensure minimal Capacitor app
        script: |
          set -euxo pipefail
          # Create tiny app files if your repo doesn't have them yet
          test -f package.json || echo '{ "name":"glowup","version":"1.0.0","private":true }' > package.json
          test -f capacitor.config.json || cat > capacitor.config.json <<'EOF'
          { "appId": "com.mathe.glowup", "appName": "GlowUp Money", "webDir": "web", "bundledWebRuntime": false }
          EOF
          mkdir -p web
          test -f web/index.html || echo '<!doctype html><title>GlowUp</title><body>Simulator build</body>' > web/index.html

      - name: Install Capacitor deps
        script: |
          set -euxo pipefail
          npm i -D @capacitor/cli @capacitor/core @capacitor/ios

      - name: Add & sync iOS + CocoaPods
        script: |
          set -euxo pipefail
          npx cap add ios || true
          npx cap sync ios
          cd ios/App
          pod install --no-repo-update
          cd ../..

      - name: Build for Simulator (unsigned)
        script: |
          set -euxo pipefail
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Package .app
        script: |
          set -euxo pipefail
          APP_PATH=$(find build/Build/Products -type d -name "App.app" | head -n1)
          if [ -z "$APP_PATH" ]; then
            echo "Could not find App.app in build products"
            ls -R build/Build/Products || true
            exit 1
          fi
          ditto -c -k --sequesterRsrc --keepParent "$APP_PATH" App-simulator.zip

    artifacts:
      - App-simulator.zip
